// src/react/components/ad-label.tsx
import type { ReactNode } from "react";
import { useVideContext } from "../context.js";
import { useAdState } from "../use-ad-state.js";

export interface AdLabelProps {
	className?: string;
	children?: ReactNode;
}

export function AdLabel({ className, children }: AdLabelProps) {
	const player = useVideContext();
	const { active } = useAdState(player);

	if (!player || !active) return null;

	return (
		<div className={["vide-ad-label", className].filter(Boolean).join(" ")}>
			{children ?? "Ad"}
		</div>
	);
}

// src/svelte/components/AdLabel.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import { useAdState } from "../use-ad-state.svelte.js";

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
const adState = useAdState(getPlayer);
</script>

{#if adState.active}
	<div class={["vide-ad-label", className].filter(Boolean).join(" ")}>
		{#if children}
			{@render children()}
		{:else}
			Ad
		{/if}
	</div>
{/if}
