// src/react/components/ad-learn-more.tsx
import { type ReactNode, useCallback, useMemo } from "react";
import { useVideContext } from "../context.js";
import { IconExternalLink } from "../icons.js";
import { useAdState } from "../use-ad-state.js";

function hostname(url: string): string {
	try {
		return new URL(url).hostname;
	} catch {
		return url;
	}
}

export interface AdLearnMoreProps {
	className?: string;
	children?: ReactNode;
}

export function AdLearnMore({ className, children }: AdLearnMoreProps) {
	const player = useVideContext();
	const { active, meta } = useAdState(player);

	const onClick = useCallback(() => {
		if (!player || !meta?.clickThrough) return;
		player.el.click();
		window.open(meta.clickThrough, "_blank");
		player.el.pause();
	}, [player, meta]);

	const host = useMemo(
		() => (meta?.clickThrough ? hostname(meta.clickThrough) : ""),
		[meta?.clickThrough],
	);

	if (!player || !active || !meta?.clickThrough) return null;

	return (
		<button
			type="button"
			className={["vide-ad-cta", className].filter(Boolean).join(" ")}
			onClick={onClick}
		>
			{children ?? (
				<>
					<span className="vide-ad-cta__icon">
						<IconExternalLink />
					</span>
					<span className="vide-ad-cta__body">
						{meta.adTitle && (
							<span className="vide-ad-cta__title">
								{meta.adTitle}
							</span>
						)}
						<span className="vide-ad-cta__url">{host}</span>
					</span>
				</>
			)}
		</button>
	);
}

// src/svelte/components/AdLearnMore.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import IconExternalLink from "../icons/IconExternalLink.svelte";
import { useAdState } from "../use-ad-state.svelte.js";

function hostname(url: string): string {
	try {
		return new URL(url).hostname;
	} catch {
		return url;
	}
}

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
const adState = useAdState(getPlayer);

function onClick() {
	const p = getPlayer();
	if (!p || !adState.meta?.clickThrough) return;
	p.el.click();
	window.open(adState.meta.clickThrough, "_blank");
	p.el.pause();
}
</script>

{#if adState.active && adState.meta?.clickThrough}
	<button
		type="button"
		class={["vide-ad-cta", className].filter(Boolean).join(" ")}
		onclick={onClick}
	>
		{#if children}
			{@render children()}
		{:else}
			<span class="vide-ad-cta__icon">
				<IconExternalLink />
			</span>
			<span class="vide-ad-cta__body">
				{#if adState.meta.adTitle}
					<span class="vide-ad-cta__title">{adState.meta.adTitle}</span>
				{/if}
				<span class="vide-ad-cta__url">{hostname(adState.meta.clickThrough)}</span>
			</span>
		{/if}
	</button>
{/if}
