// src/react/components/ad-overlay.tsx
import { type ReactNode, useCallback } from "react";
import { useVideContext } from "../context.js";
import { useAdState } from "../use-ad-state.js";

export interface AdOverlayProps {
	className?: string;
	children?: ReactNode;
}

export function AdOverlay({ className, children }: AdOverlayProps) {
	const player = useVideContext();
	const { active, meta } = useAdState(player);

	const handleClick = useCallback(() => {
		if (!player) return;
		player.el.click();
		const url = meta?.clickThrough;
		if (url) {
			window.open(url, "_blank");
			player.el.pause();
		} else {
			if (player.el.paused) {
				Promise.resolve(player.el.play()).catch(() => {});
			} else {
				player.el.pause();
			}
		}
	}, [player, meta]);

	if (!player || !active) return null;

	return (
		/* Overlay is a transparent full-area click target on top of the ad video.
		   Keyboard users interact via the underlying player controls, not the overlay. */
		// biome-ignore lint/a11y/useKeyWithClickEvents: overlay delegates to player controls for keyboard access
		<div
			className={["vide-ad-overlay", className].filter(Boolean).join(" ")}
			onClick={handleClick}
		>
			{children}
		</div>
	);
}

// src/svelte/components/AdOverlay.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import { useAdState } from "../use-ad-state.svelte.js";

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
const adState = useAdState(getPlayer);

function onClick() {
	const p = getPlayer();
	if (!p) return;
	p.el.click();
	const url = adState.meta?.clickThrough;
	if (url) {
		window.open(url, "_blank");
		p.el.pause();
	} else {
		if (p.el.paused) {
			Promise.resolve(p.el.play()).catch(() => {});
		} else {
			p.el.pause();
		}
	}
}
</script>

{#if adState.active}
	<div
		class={["vide-ad-overlay", className].filter(Boolean).join(" ")}
		onclick={onClick}
		role="button"
		tabindex="-1"
	>
		{#if children}
			{@render children()}
		{/if}
	</div>
{/if}
