// src/react/components/big-play-button.tsx
import { type ReactNode, useCallback, useContext } from "react";
import { VideContext } from "../context.js";
import { IconPlay } from "../icons.js";

export interface BigPlayButtonProps {
	className?: string;
	children?: ReactNode;
}

export function BigPlayButton({ className, children }: BigPlayButtonProps) {
	const player = useContext(VideContext)?.player ?? null;

	const onClick = useCallback(() => {
		if (!player) return;
		if (player.state === "ended") {
			const p = player;
			function onReady({ to }: { from: string; to: string }): void {
				if (to === "ready") {
					p.off("statechange", onReady);
					p.play().catch(() => {});
				}
			}
			p.on("statechange", onReady);
			p.el.currentTime = 0;
			p.el.load();
			return;
		}
		player.play().catch(() => {});
	}, [player]);

	return (
		<button
			type="button"
			className={["vide-bigplay", className].filter(Boolean).join(" ")}
			aria-label="Play video"
			onClick={onClick}
		>
			{children ?? <IconPlay />}
		</button>
	);
}

// src/svelte/components/BigPlayButton.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import IconPlay from "../icons/IconPlay.svelte";

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);

function onClick() {
	const p = getPlayer();
	if (!p) return;
	if (p.state === "ended") {
		function onReady({ to }: { from: string; to: string }): void {
			if (to === "ready") {
				p.off("statechange", onReady);
				p.play().catch(() => {});
			}
		}
		p.on("statechange", onReady);
		p.el.currentTime = 0;
		p.el.load();
		return;
	}
	p.play().catch(() => {});
}
</script>

<button
	type="button"
	class={["vide-bigplay", className].filter(Boolean).join(" ")}
	aria-label="Play video"
	onclick={onClick}
>
	{#if children}
		{@render children()}
	{:else}
		<IconPlay />
	{/if}
</button>
