// src/react/components/click-play.tsx
import { useCallback, useContext, useRef } from "react";
import { isAdState } from "../../ui/state.js";
import { VideContext } from "../context.js";

const DBLCLICK_DELAY = 200;

export interface ClickPlayProps {
	className?: string;
	enableFullscreen?: boolean;
}

export function ClickPlay({
	className,
	enableFullscreen = true,
}: ClickPlayProps) {
	const player = useContext(VideContext)?.player ?? null;
	const clickTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

	const togglePlay = useCallback(() => {
		if (!player) return;
		if (player.state === "playing" || player.state === "ad:playing") {
			player.pause();
		} else {
			player.play().catch(() => {});
		}
	}, [player]);

	const toggleFullscreen = useCallback(() => {
		if (!enableFullscreen) return;
		const target =
			(player?.el.closest(".vide-ui") as HTMLElement | null) ??
			player?.el.parentElement;
		if (!target) return;
		if (document.fullscreenElement != null) {
			document.exitFullscreen().catch(() => {});
		} else if (target.requestFullscreen) {
			target.requestFullscreen().catch(() => {});
		}
	}, [player, enableFullscreen]);

	const onClick = useCallback(() => {
		if (!player) return;

		if (isAdState(player.state)) {
			player.el.click();
			togglePlay();
			return;
		}

		if (clickTimer.current !== null) {
			clearTimeout(clickTimer.current);
			clickTimer.current = null;
			toggleFullscreen();
			return;
		}

		clickTimer.current = setTimeout(() => {
			clickTimer.current = null;
			togglePlay();
		}, DBLCLICK_DELAY);
	}, [player, togglePlay, toggleFullscreen]);

	return (
		<div
			className={["vide-clickplay", className].filter(Boolean).join(" ")}
			onClick={onClick}
		/>
	);
}

// src/svelte/components/ClickPlay.svelte
<script lang="ts">
import { getContext, onDestroy } from "svelte";
import { isAdState } from "../../ui/state.js";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";

const DBLCLICK_DELAY = 200;

interface Props {
	class?: string;
	enableFullscreen?: boolean;
}

const { class: className, enableFullscreen = true }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
let clickTimer: ReturnType<typeof setTimeout> | null = null;

function togglePlay(): void {
	const p = getPlayer();
	if (!p) return;
	if (p.state === "playing" || p.state === "ad:playing") {
		p.pause();
	} else {
		p.play().catch(() => {});
	}
}

function toggleFullscreen(): void {
	if (!enableFullscreen) return;
	const p = getPlayer();
	const target =
		(p?.el.closest(".vide-ui") as HTMLElement | null) ?? p?.el.parentElement;
	if (!target) return;
	if (document.fullscreenElement != null) {
		document.exitFullscreen().catch(() => {});
	} else if (target.requestFullscreen) {
		target.requestFullscreen().catch(() => {});
	}
}

function onClick(): void {
	const p = getPlayer();
	if (!p) return;

	if (isAdState(p.state)) {
		p.el.click();
		togglePlay();
		return;
	}

	if (clickTimer !== null) {
		clearTimeout(clickTimer);
		clickTimer = null;
		toggleFullscreen();
		return;
	}

	clickTimer = setTimeout(() => {
		clickTimer = null;
		togglePlay();
	}, DBLCLICK_DELAY);
}

onDestroy(() => {
	if (clickTimer !== null) {
		clearTimeout(clickTimer);
		clickTimer = null;
	}
});
</script>

<div
	class={["vide-clickplay", className].filter(Boolean).join(" ")}
	onclick={onClick}
	role="presentation"
></div>
