// src/svelte/components/AdSkip.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import IconSkipForward from "../icons/IconSkipForward.svelte";
import { useAdState } from "../use-ad-state.svelte.js";

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
const adState = useAdState(getPlayer);
let canSkip = $state(false);
let countdown = $state(0);

$effect(() => {
	const p = getPlayer();
	if (!p) return;

	const onTimeUpdate = ({ currentTime }: { currentTime: number }) => {
		if (
			!adState.active ||
			!adState.meta ||
			adState.meta.skipOffset === undefined
		)
			return;
		if (currentTime >= adState.meta.skipOffset) {
			canSkip = true;
		} else {
			canSkip = false;
			countdown = Math.max(0, Math.ceil(adState.meta.skipOffset - currentTime));
		}
	};

	p.on("timeupdate", onTimeUpdate);
	return () => p.off("timeupdate", onTimeUpdate);
});

function onClick() {
	const p = getPlayer();
	if (!p || !canSkip || !adState.meta) return;
	p.emit("ad:skip", { adId: adState.meta.adId });
}
</script>

{#if adState.active && adState.meta && adState.meta.skipOffset !== undefined}
	<button
		type="button"
		class={["vide-skip", !canSkip && "vide-skip--disabled", className].filter(Boolean).join(" ")}
		aria-label="Skip ad"
		onclick={onClick}
		disabled={!canSkip}
	>
		{#if children}
			{@render children()}
		{:else}
			<span class="vide-skip__label">
				{canSkip ? "Skip Ad" : `Skip in ${countdown}s`}
			</span>
			<IconSkipForward />
		{/if}
	</button>
{/if}

// src/react/components/ad-skip.tsx
import { type ReactNode, useCallback, useState } from "react";
import { useVideContext } from "../context.js";
import { IconSkipForward } from "../icons.js";
import { useAdState } from "../use-ad-state.js";
import { useVideEvent } from "../use-vide-event.js";

export interface AdSkipProps {
	className?: string;
	children?: ReactNode;
}

export function AdSkip({ className, children }: AdSkipProps) {
	const player = useVideContext();
	const { active, meta } = useAdState(player);
	const [canSkip, setCanSkip] = useState(false);
	const [countdown, setCountdown] = useState(0);

	useVideEvent(player, "timeupdate", ({ currentTime }) => {
		if (!active || !meta || meta.skipOffset === undefined) return;
		if (currentTime >= meta.skipOffset) {
			setCanSkip(true);
		} else {
			setCanSkip(false);
			setCountdown(Math.max(0, Math.ceil(meta.skipOffset - currentTime)));
		}
	});

	const onClick = useCallback(() => {
		if (!player || !canSkip || !meta) return;
		player.emit("ad:skip", { adId: meta.adId });
	}, [player, canSkip, meta]);

	if (!player || !active || !meta || meta.skipOffset === undefined) return null;

	return (
		<button
			type="button"
			className={["vide-skip", !canSkip && "vide-skip--disabled", className]
				.filter(Boolean)
				.join(" ")}
			aria-label="Skip ad"
			onClick={onClick}
			disabled={!canSkip}
		>
			{children ?? (
				<>
					<span className="vide-skip__label">
						{canSkip ? "Skip Ad" : `Skip in ${countdown}s`}
					</span>
					<IconSkipForward />
				</>
			)}
		</button>
	);
}
