// src/svelte/components/ErrorDisplay.svelte
<script lang="ts">
import { getContext } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";

interface Props {
	class?: string;
}

const { class: className }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
let message = $state("");

$effect(() => {
	const p = getPlayer();
	if (!p) return;
	const handler = ({ message: msg }: { message: string }) => {
		message = msg;
	};
	p.on("error", handler);
	return () => p.off("error", handler);
});
</script>

<div role="alert" class={["vide-error", className].filter(Boolean).join(" ")}>
	<span class="vide-error__message">{message}</span>
</div>

// src/react/components/error-display.tsx
import { useContext, useState } from "react";
import { VideContext } from "../context.js";
import { useVideEvent } from "../use-vide-event.js";

export interface ErrorDisplayProps {
	className?: string;
}

export function ErrorDisplay({ className }: ErrorDisplayProps) {
	const player = useContext(VideContext)?.player ?? null;
	const [message, setMessage] = useState("");

	useVideEvent(player, "error", ({ message }: { message: string }) => {
		setMessage(message);
	});

	return (
		<div
			role="alert"
			className={["vide-error", className].filter(Boolean).join(" ")}
		>
			<span className="vide-error__message">{message}</span>
		</div>
	);
}
