// src/svelte/components/MuteButton.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import IconVolumeHigh from "../icons/IconVolumeHigh.svelte";
import IconVolumeLow from "../icons/IconVolumeLow.svelte";
import IconVolumeMute from "../icons/IconVolumeMute.svelte";

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
let muted = $state(false);
let volume = $state(1);

$effect(() => {
	const p = getPlayer();
	if (!p) return;
	const sync = () => {
		muted = p.muted || p.volume === 0;
		volume = p.volume;
	};
	p.el.addEventListener("volumechange", sync);
	sync();
	return () => {
		p.el.removeEventListener("volumechange", sync);
	};
});

function onClick() {
	const p = getPlayer();
	if (!p) return;
	p.muted = !p.muted;
}
</script>

<button
	type="button"
	class={["vide-mute", className].filter(Boolean).join(" ")}
	aria-label={muted ? "Unmute" : "Mute"}
	data-tooltip={muted ? "Unmute" : "Mute"}
	data-muted={muted || undefined}
	onclick={onClick}
>
	{#if children}
		{@render children()}
	{:else if muted}
		<IconVolumeMute />
	{:else if volume < 0.5}
		<IconVolumeLow />
	{:else}
		<IconVolumeHigh />
	{/if}
</button>

// src/react/components/mute-button.tsx
import { type ReactNode, useCallback, useEffect, useState } from "react";
import { useVideContext } from "../context.js";
import { IconVolumeHigh, IconVolumeLow, IconVolumeMute } from "../icons.js";

export interface MuteButtonProps {
	className?: string;
	children?: ReactNode;
}

export function MuteButton({ className, children }: MuteButtonProps) {
	const player = useVideContext();
	const [muted, setMuted] = useState(false);
	const [volume, setVolume] = useState(1);

	useEffect(() => {
		if (!player) return;
		const sync = () => {
			setMuted(player.muted || player.volume === 0);
			setVolume(player.volume);
		};
		player.el.addEventListener("volumechange", sync);
		sync();
		return () => {
			player.el.removeEventListener("volumechange", sync);
		};
	}, [player]);

	const onClick = useCallback(() => {
		if (!player) return;
		player.muted = !player.muted;
	}, [player]);

	let defaultIcon: ReactNode;
	if (muted) {
		defaultIcon = <IconVolumeMute />;
	} else if (volume < 0.5) {
		defaultIcon = <IconVolumeLow />;
	} else {
		defaultIcon = <IconVolumeHigh />;
	}

	return (
		<button
			type="button"
			className={["vide-mute", className].filter(Boolean).join(" ")}
			aria-label={muted ? "Unmute" : "Mute"}
			data-tooltip={muted ? "Unmute" : "Mute"}
			onClick={onClick}
			data-muted={muted || undefined}
		>
			{children ?? defaultIcon}
		</button>
	);
}
