// src/svelte/components/PlayButton.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Snippet } from "svelte";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";
import type { PlayerState } from "../helpers.js";
import IconPause from "../icons/IconPause.svelte";
import IconPlay from "../icons/IconPlay.svelte";

interface Props {
	class?: string;
	children?: Snippet;
}

const { class: className, children }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
let playing = $state(false);

$effect(() => {
	const p = getPlayer();
	if (!p) return;
	const handler = ({ to }: { from: PlayerState; to: PlayerState }) => {
		if (to === "playing" || to === "ad:playing") {
			playing = true;
		} else if (
			to === "paused" ||
			to === "ready" ||
			to === "ended" ||
			to === "ad:paused"
		) {
			playing = false;
		}
	};
	p.on("statechange", handler);
	return () => p.off("statechange", handler);
});

function onClick() {
	const p = getPlayer();
	if (!p) return;
	if (p.state === "playing" || p.state === "ad:playing") {
		p.pause();
	} else {
		p.play().catch(() => {});
	}
}
</script>

<button
	type="button"
	class={["vide-play", className].filter(Boolean).join(" ")}
	aria-label={playing ? "Pause" : "Play"}
	data-tooltip={playing ? "Pause" : "Play"}
	data-playing={playing || undefined}
	onclick={onClick}
>
	{#if children}
		{@render children()}
	{:else if playing}
		<IconPause />
	{:else}
		<IconPlay />
	{/if}
</button>

// src/react/components/play-button.tsx
import { type ReactNode, useCallback, useState } from "react";
import type { PlayerState } from "../../types.js";
import { useVideContext } from "../context.js";
import { IconPause, IconPlay } from "../icons.js";
import { useVideEvent } from "../use-vide-event.js";

export interface PlayButtonProps {
	className?: string;
	children?: ReactNode;
}

export function PlayButton({ className, children }: PlayButtonProps) {
	const player = useVideContext();
	const [playing, setPlaying] = useState(false);

	useVideEvent(
		player,
		"statechange",
		({ to }: { from: PlayerState; to: PlayerState }) => {
			if (to === "playing" || to === "ad:playing") {
				setPlaying(true);
			} else if (
				to === "paused" ||
				to === "ready" ||
				to === "ended" ||
				to === "ad:paused"
			) {
				setPlaying(false);
			}
		},
	);

	const onClick = useCallback(() => {
		if (!player) return;
		if (player.state === "playing" || player.state === "ad:playing") {
			player.pause();
		} else {
			player.play().catch(() => {});
		}
	}, [player]);

	return (
		<button
			type="button"
			className={["vide-play", className].filter(Boolean).join(" ")}
			aria-label={playing ? "Pause" : "Play"}
			data-tooltip={playing ? "Pause" : "Play"}
			onClick={onClick}
			data-playing={playing || undefined}
		>
			{children ?? (playing ? <IconPause /> : <IconPlay />)}
		</button>
	);
}
