// src/svelte/components/TimeDisplay.svelte
<script lang="ts">
import { getContext } from "svelte";
import { formatTime } from "../helpers.js";
import { type PlayerGetter, VIDE_PLAYER_KEY } from "../context.js";

interface Props {
	class?: string;
	separator?: string;
}

const { class: className, separator = "/" }: Props = $props();

const getPlayer = getContext<PlayerGetter>(VIDE_PLAYER_KEY);
let currentTime = $state(0);
let duration = $state(0);

$effect(() => {
	const p = getPlayer();
	if (!p) return;
	const handler = (data: { currentTime: number; duration: number }) => {
		currentTime = data.currentTime;
		duration = data.duration;
	};
	p.on("timeupdate", handler);
	return () => p.off("timeupdate", handler);
});
</script>

<div class={["vide-time", className].filter(Boolean).join(" ")} aria-label="Time">
	<span>{formatTime(currentTime)}</span>
	<span>{separator}</span>
	<span>{formatTime(duration)}</span>
</div>

// src/react/components/time-display.tsx
import { useState } from "react";
import { formatTime } from "../../ui/utils.js";
import { useVideContext } from "../context.js";
import { useVideEvent } from "../use-vide-event.js";

export interface TimeDisplayProps {
	className?: string;
	separator?: string;
}

export function TimeDisplay({ className, separator = "/" }: TimeDisplayProps) {
	const player = useVideContext();
	const [currentTime, setCurrentTime] = useState(0);
	const [duration, setDuration] = useState(0);

	useVideEvent(player, "timeupdate", (data) => {
		setCurrentTime(data.currentTime);
		setDuration(data.duration);
	});

	return (
		<div
			className={["vide-time", className].filter(Boolean).join(" ")}
			aria-label="Time"
		>
			<span className="vide-time__current">{formatTime(currentTime)}</span>
			<span className="vide-time__separator">{separator}</span>
			<span className="vide-time__duration">{formatTime(duration)}</span>
		</div>
	);
}
